name: 'Delete a Kubernetes namespace'
description: 'Delete a complete Kubernetes namespace. Useful for cleanup actions'
inputs:
  namespace:
    description: 'Kubernetes namespace to delete'
    required: true
runs:
  using: 'docker'
  image: docker://thecodingmachine/deeployer:latest
  args:
    - deeployer-k8s
    - delete
    - "--namespace"
    - ${{ inputs.namespace }}

branding:
  icon: 'cloud'
  color: 'red'
